### ISSUE TITLE
I noticed 0-RTT and OCSP stapling not working with BoringSSL

### ISSUE THREAD

**Issue by Zxilly** [RanadeepPolavarapu/docker-nginx-http3#10]
How can I fix it?
Any suggestion plz.

**Comment by RanadeepPolavarapu** [comment]
Hello,

Could you please share reproduction steps? Also, can you please share nginx conf?

**Comment by Zxilly** [comment]
When I launched nginx,it tolded me that "nginx: [warn] "ssl_stapling" ignored, not supported"
And I set ssl_early_data on; in my nginx conf,but ssllabs.com tel me that 0-RTT not working.

**Comment by RanadeepPolavarapu** [comment]
Can you please check with this https://github.com/RanadeepPolavarapu/docker-nginx-http3#testing-0-rtt?

**Comment by RanadeepPolavarapu** [comment]
BoringSSL doesn't support OCSP. You can patch this yourself if you want to risk it with this [patch](https://raw.githubusercontent.com/kn007/patch/35f2b0decbc510f2c8adab9261e3d46ba1398e33/Enable_BoringSSL_OCSP.patch).

**Comment by RanadeepPolavarapu** [comment]
0-RTT out of the box without OCSP should work as shown in the README.

**Comment by Zxilly** [comment]
> Quiche (for H3) uses BoringSSL and BoringSSL doesn't support OCSP. You can patch this yourself if you want to risk it with this [patch](https://raw.githubusercontent.com/kn007/patch/35f2b0decbc510f2c8adab9261e3d46ba1398e33/Enable_BoringSSL_OCSP.patch).

Thank you for your help,I'll try this solution.

If it still not work,i'll reopen this issue.

Tks for your help
