### ISSUE TITLE
Could you add nginx_cookie_flag_module ?

### ISSUE THREAD

**Issue by budarin** [RanadeepPolavarapu/docker-nginx-http3#11]
Please add nginx_cookie_flag_module to image

**Comment by RanadeepPolavarapu** [comment]
Resolved in 1b6c7de14b87ff13b7acc452317157158d8e94aa. Image has been built and pushed. Ready to be used.

**Comment by budarin** [comment]
thanks a lot!

**Comment by RanadeepPolavarapu** [comment]
You’re welcome :)

**Comment by budarin** [comment]
@RanadeepPolavarapu thanks! )
