### ISSUE TITLE
Hybrid rsa and ecdsa certificates

### ISSUE THREAD

**Issue by woosungchoi** [RanadeepPolavarapu/docker-nginx-http3#14]
https://scotthelme.co.uk/hybrid-rsa-and-ecdsa-certificates-with-nginx/

I'm using Hybrid RSA and ECDSA certificates with Nginx.

But this image support just one RSA certificate.

**Comment by RanadeepPolavarapu** [comment]
Does this work for BoringSSL over OpenSSL?

**Comment by woosungchoi** [comment]
I don't know.

But official nginx image works.

https://hub.docker.com/layers/nginx/library/nginx/1.19.3-alpine/images/sha256-4e21f77cde9aaeb846dc799b934a42b66939d19755d98829b705270e916c7479?context=explore
