### ISSUE TITLE
Could you add Support OCSP stapling

### ISSUE THREAD

**Issue by woosungchoi** [RanadeepPolavarapu/docker-nginx-http3#15]
https://github.com/kn007/patch/blob/master/Enable_BoringSSL_OCSP.patch

I think it's a good idea to add OCSP stapling to Docker Image.

**Comment by RanadeepPolavarapu** [comment]
@woosungchoi I tried this and the build failed I assume due to conflict with quiche's BoringSSL. Please try it out and let me know if you got it working.
