### ISSUE TITLE
Add nginx-http-json-log

### ISSUE THREAD

**Issue by budarin** [RanadeepPolavarapu/docker-nginx-http3#21]
Please add  `nginx-http-json-log`  to make it convenient to use logs with `grafana/loki` and `grafana`
https://grafana.com/grafana/dashboards/12559

**Comment by budarin** [comment]
@RanadeepPolavarapu are you here? :)

**Comment by RanadeepPolavarapu** [comment]
Hi @budarin,

I checked a few JSON logging options and seems the modules are quite old and one states it's not production ready.

Are you not able to use the default JSON escaping option as described in https://stackoverflow.com/a/42564710/1757703 with nginx's JSON escape flag (http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format)?

**Comment by budarin** [comment]
thanks!
I'll try
