### ISSUE TITLE
Add ARM support

### ISSUE THREAD

**Issue by TheWiresharkGuy** [RanadeepPolavarapu/docker-nginx-http3#24]
Hi,

Do you plan on adding Docker multi-arch builds for this projet ?

I would be really interested!

**Comment by alekkxl** [comment]
you can see docker wakongka/nginx i fork RanadeepPolavarapu/docker-nginx-http3 and edit

**Comment by RanadeepPolavarapu** [comment]
> Hi,
> 
> Do you plan on adding Docker multi-arch builds for this projet ?
> 
> I would be really interested!

ARM support has been added.

![image](https://user-images.githubusercontent.com/7084995/120055126-09b11580-c002-11eb-88e8-062331ca0e69.png)
