### ISSUE TITLE
cannot even acess https

### ISSUE THREAD

**Issue by MichaelPan1026** [RanadeepPolavarapu/docker-nginx-http3#32]
http(port 80) works well, but i cannot access https(port 443), and i cannot customize root directory of the website, i have edited `location / {root xx}` in default.conf, but when i `cat access.log`, it would say `404 /etc/nginx/html/index.html`.

i run with the command(https wont work):
```
docker run --name nginx -p 80:80 -p 443:443/tcp -p 443:443/udp -v /home/admin/trojan-go/nginx:/etc/nginx/conf.d -v /home/admin/trojan-go/nginx/cert:/etc/ssl -v /var/log/nginx:/var/log/nginx -v /var/www/public:/etc/nginx/html -v /etc/localtime:/etc/localtime  --restart=always -d ranadeeppolavarapu/nginx-http3
```
And i deleted the http3 stuff and run with the offical nginx image:
```
docker run --name nginx -p 80:80 -p 443:443/tcp -p 443:443/udp -v /home/admin/trojan-go/nginx:/etc/nginx/conf.d -v /home/admin/trojan-go/nginx/cert:/etc/ssl -v /var/log/nginx:/var/log/nginx -v /var/www/public:/etc/nginx/html -v /etc/localtime:/etc/localtime  --restart=always -d nginx
````
The https will works well.

**Comment by RanadeepPolavarapu** [comment]
@MichaelPan1026 Please try again with latest image.

**Comment by MichaelPan1026** [comment]
> @MichaelPan1026 Please try again with latest image.

OK, now everything goes fine. But `$tls1_3_early_data` seems to be a invalid variable. Delete it and docker works well.
