### ISSUE TITLE
Could you upgrade nginx to the latest or stable version, please?

### ISSUE THREAD

**Issue by budarin** [RanadeepPolavarapu/docker-nginx-http3#33]
try to use `proxy_cookie_flags`, but it's not present in 1.16.1  version

**Comment by RanadeepPolavarapu** [comment]
[quiche (for HTTP/3) is currently only supported for `1.16.x` version.](https://github.com/cloudflare/quiche/tree/master/extras/nginx#building)

**Comment by budarin** [comment]
what??
it will not be supported in higher versions??? :(

**Comment by RanadeepPolavarapu** [comment]
> what??
> it will not be supported in higher versions??? :(

Unfortunately that is the case until nginx releases official H3 support without quiche.
![image](https://user-images.githubusercontent.com/7084995/122837103-85c91100-d2c1-11eb-9102-384472a57ccc.png)

**Comment by budarin** [comment]
:( thanks
