### ISSUE TITLE
[HELP] Image not running

### ISSUE THREAD

**Issue by ihmc3jn09hk** [RanadeepPolavarapu/docker-nginx-http3#4]
I pulled the image with:
``$docker pull ranadeeppolavarapu/nginx-http3``
and then:
``$sudo docker run -it ranadeeppolavarapu/nginx-http3 bin/sh``

The packages e.g. gcc, git etc are not installed and it seems there is no configuration set for Nginx.
Could you please point me out the issue?

**Comment by RanadeepPolavarapu** [comment]
@ihmc3jn09hk I have updated the base image to include a default H3 config. Please see *h3.nginxconf*.

https://github.com/RanadeepPolavarapu/docker-nginx-http3/blob/5946dd408cc2ccdccbcce16208f220e75ff3e685/h3.nginxconf#L12

**Comment by ihmc3jn09hk** [comment]
Much thanks.
Apart from the configuration, does the image removed all development kits? Since there is only the compiled Nginx.
Will try it out tmr.
I just tried following the instructions from Cloudflare and successfully built the Nginx. Yet don't why 
``make install`` failed. But it runs. However, can't communicate through http3 (chrome cranky). Hope that ur image will help.

**Comment by RanadeepPolavarapu** [comment]
Yes, it does. It is meant to be used a production image. Are you using Chrome Canary with the flags on the README?

**Comment by ihmc3jn09hk** [comment]
Used the updated image ( 2X MB one ) and the provided h3.config.conf and nginx.conf files however still got no luck. I customized it with my local network and port as you may see in the image.
Would it be the issue of the page is not stressful enough trigger the http3 mechanism??
![Capture](https://user-images.githubusercontent.com/13495525/68123762-cc30f700-ff48-11e9-88fb-bbd3d1fdaf18.JPG)

**Comment by RanadeepPolavarapu** [comment]
Are you using Chrome Canary with the flags?

**Comment by RanadeepPolavarapu** [comment]
You need an H3 client. Chrome Canary currently has it behind feature flags. You need to use the following CLI args and open Chrome. Alternatively, you can set them behind `chrome://flags`. 

Here are the CLI args with the feature flags. 

```bat
--flag-switches-begin --enable-quic --quic-version=h3-23 --enable-features=EnableTLS13EarlyData --flag-switches-end
```

I am not entirely sure how to open Chrome via CLI on Windows so, you can do it through the GUI at `chrome://flags`.

**Comment by ihmc3jn09hk** [comment]
I think I did it already
![Capture](https://user-images.githubusercontent.com/13495525/68124347-21b9d380-ff4a-11e9-9963-e1102762c466.JPG)

**Comment by RanadeepPolavarapu** [comment]
Can you confirm that the GUI shows the flags enabled?

https://blog.cloudflare.com/http3-the-past-present-and-future/#using-google-chrome-as-an-http-3-client -- This may help a bit more for Chrome.

**Comment by RanadeepPolavarapu** [comment]
Oh. Also, did you forward the port under UDP from the container? H3 uses UDP. 

`docker run -p 80:80 -p 443:443/tcp -p 443:443/udp ...`

**Comment by ihmc3jn09hk** [comment]
I pretty much confirm that is how flags work in windows because when I add an extra flag "--incognito", it does start with Incognito mode.
Would it be something related to the self-signed certificate is not trusted ?

**Comment by RanadeepPolavarapu** [comment]
Yeah that may something to do with it. I was running with a valid CA signed cert. I am not 100% sure if Chrome doesn't upgrade to H3 if cert is invalid.

**Comment by ihmc3jn09hk** [comment]
> Oh. Also, did you forward the port under UDP from the container? H3 uses UDP.
> 
> `docker run -p 80:80 -p 443:443/tcp -p 443:443/udp ...`
> 
> If only TCP is forwarding (which is the default), you will connect via H2.



> Oh. Also, did you forward the port under UDP from the container? H3 uses UDP.
> 
> `docker run -p 80:80 -p 443:443/tcp -p 443:443/udp ...`
> 
> If only TCP is forwarding (which is the default), you will connect via H2.

Good to know and I tried
``sudo docker run -p 4433:4433/tcp -p 4433:4433/udp -it 3331eae68269 bin/sh``
where 3331eae68269 is your image ID in my VM.
But still no luck

**Comment by RanadeepPolavarapu** [comment]
I'll try it locally on a self signed cert once I get home. I haven't tested this locally at all. 

My actual deployed setup is exactly that with a valid Let's Encrypt cert.

**Comment by RanadeepPolavarapu** [comment]
Side note (this may be useful): To test if H3 is enabled client side you can go to https://blog.cloudflare.com/ (they are running the blog with H3 enabled).

**Comment by ihmc3jn09hk** [comment]
> t with a valid L

I see. Thanks alot for the responses. Maybe I should try it with some free dns domain with some free CA with some more time.

**Comment by RanadeepPolavarapu** [comment]
No problem.  I'll update you once I try this locally with self signed to see if that's the true issue.

**Comment by ihmc3jn09hk** [comment]
Please see the image. The client side I am using ( Chrome Canary ) in fact is in http3-enabled configuration.
I think we pretty much nailed it !!! The certification shall be the key. 
![Capture](https://user-images.githubusercontent.com/13495525/68125858-79a60980-ff4d-11e9-8d29-2db34cfcc920.JPG)

**Comment by ihmc3jn09hk** [comment]
Verified !

![Capture](https://user-images.githubusercontent.com/13495525/68131543-34d3a000-ff58-11e9-8af1-0ea5d2a97c8a.JPG)

**Comment by RanadeepPolavarapu** [comment]
Woohoo! Awesome. I will update the docs to put a note that this needs a valid certificate enabled. Thanks a lot for verifying. 😄

**Comment by ihmc3jn09hk** [comment]
You are welcome. 
Thanks for your sharing too.
