### ISSUE TITLE
Css files content type error

### ISSUE THREAD

**Issue by TheYkk** [RanadeepPolavarapu/docker-nginx-http3#6]
![image](https://user-images.githubusercontent.com/21688838/68482634-0d781e00-024b-11ea-94a1-d2721f2ee590.png)

i using this docker image for my website -> https://gitlab.com/theykk/me

But some css files don't loading correctly.
How can i fix this issue?

**Comment by RanadeepPolavarapu** [comment]
@TheYkk Hi, I don't think that's an issue with the image, but more so your Nginx config. Have a look at nginx.conf.

https://github.com/RanadeepPolavarapu/docker-nginx-http3/blob/0a65cd0ca1ba062dc14092dbf803b796131b39d9/nginx.conf#L35

**Comment by TheYkk** [comment]
I am using yours nginx configs https://gitlab.com/TheYkk/me/blob/master/nginx.conf

**Comment by TheYkk** [comment]
![image](https://user-images.githubusercontent.com/21688838/68483462-a9eef000-024c-11ea-90b8-91b2fd643692.png)
![image](https://user-images.githubusercontent.com/21688838/68483467-ad827700-024c-11ea-9c10-0b07e0a8d352.png)

Some files correct some files wrong

**Comment by RanadeepPolavarapu** [comment]
I am not entirely sure. I checked my deployed H3 server and all JS/CSS are showing the correct content types.

**Comment by TheYkk** [comment]
i was using this image https://github.com/nwtgck/docker-nginx-http3 and i didn't had any problem

**Comment by RanadeepPolavarapu** [comment]
@TheYkk I tried a redeploy on my app and I can't reproduce. I am serving multiple CSS and JS. I see you're behind cloudflare and your requests on your site is actually producing errors for me.

Maybe remove this? https://gitlab.com/TheYkk/me/blob/master/h3.nginx.conf#L58

**Comment by TheYkk** [comment]
i added this lines for solving my issue but didn't work.

**Comment by RanadeepPolavarapu** [comment]
Can you link me the CSS assets URL? Your website is dumping `404`s for them.

**Comment by TheYkk** [comment]
https://theykk.net/vendors/linericon/style.min.css
https://theykk.net/css/bootstrap.min.css

**Comment by TheYkk** [comment]
https://theykk.net/vendors/linericon/style.min.css
https://theykk.net/css/bootstrap.min.css

**Comment by RanadeepPolavarapu** [comment]
@TheYkk I am getting a 404 not found for both of those.

**Comment by TheYkk** [comment]
how its possible?

**Comment by TheYkk** [comment]
when tested my site  on gtmetrix everythings is fine.
https://gtmetrix.com/reports/theykk.net/IrYGeAEx

**Comment by RanadeepPolavarapu** [comment]
Ok, i verified. All the content types appear fine to me. Are you using that other image or this one currently for the deployed instance?

**Comment by TheYkk** [comment]
i build my own image with removed  more headers extension

**Comment by RanadeepPolavarapu** [comment]
Okay, sure. Let me know if you can reproduce this. I have been using this exact same image base with H2 + brotli for 2 years now and haven't run into this. The H3 is just added on my base H2 + brotli image.

**Comment by TheYkk** [comment]
my problem is unfortunately caused by Cloudflare.
cloudflare cached old settings.

**Comment by RanadeepPolavarapu** [comment]
Ahh I see. The setup I run is not behind any other proxy. Just a FYI, to my knowledge, you won't be able to as of now use H3 behind CF. CF will proxy via H2. I don't believe CF has enabled H3 for CF customers yet.

**Comment by TheYkk** [comment]
Cf open http3 for all users . Works very well.

**Comment by RanadeepPolavarapu** [comment]
Oh okay, awesome. Good to know. 👍
